{% set name = "amqp" %}
{% set version = "5.0.5" %}

package:
    name: {{ name|lower }}
    version: {{ version }}

source:
    fn: {{ name }}-{{ version }}.tar.gz
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: affdd263d8b8eb3c98170b78bf83867cdb6a14901d586e00ddb65bfe2f0c4e60

build:
    noarch: python
    number: 0
    script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
    build:
        - python
        - pip
    run:
        - python
        - vine >=1.1.3

test:
    imports:
        - amqp

about:
    home: http://github.com/celery/py-amqp
    license: BSD 3-clause
    license_family: BSD
    license_file: LICENSE
    summary: Low-level AMQP client for Python (fork of amqplib)
    doc_url: https://amqp.readthedocs.io/
    dev_url: http://github.com/celery/py-amqp/

extra:
    recipe-maintainers:
        - anguslees
        - kwilcox
        - wseaton
        - frol
