{% set name = "amqp" %}
{% set version = "5.3.1" %}
{% set tests_to_skip = " test_read_frame__windowstimeout " %}
{% set tests_to_skip = tests_to_skip + " or test_heartbeat_check_rate_default" %} # [win]

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: cddc00c725449522023bad949f70fff7b48f0b1ade74d170a6f10ab044739432
  - url: https://github.com/celery/py-{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 865f165c1ff27052e5a6af249f42659b8fa21d25279a6a8a152580fca3b0de36
    folder: gh_src

build:
  number: 0
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python
    - pip
    - setuptools >=20.6.7
    - wheel >=0.29.0
  run:
    - python
    - vine >=5.0.0,<6.0.0

test:
  source_files:
    - gh_src
  requires:
    - pip
    - pytest >=6.2.5,<=8.0.0
    - pytest-sugar >=0.9.1
    - pytest-rerunfailures >=6.0
  imports:
    - amqp.abstract_channel
    - amqp.basic_message
    - amqp.channel
    - amqp.connection
    - amqp.platform
    - amqp.protocol
    - amqp.transport
    - amqp.serialization
  commands:
    - pip check
    - pytest -xv gh_src/t/unit -k "not ({{ tests_to_skip }})"
    - pytest -xv gh_src/t/integration

about:
    home: https://github.com/celery/py-amqp
    license: BSD-3-Clause
    license_family: BSD
    license_file: LICENSE
    summary: Low-level AMQP client for Python (fork of amqplib)
    description: |
        It is maintained by the Celery project, and used by kombu as a pure python alternative when librabbitmq is not available.
        This library should be API compatible with librabbitmq.
    doc_url: https://amqp.readthedocs.io/
    dev_url: https://github.com/celery/py-amqp/

extra:
    recipe-maintainers:
        - anguslees
        - kwilcox
        - wseaton
        - frol
