travis:
  secure:
    BINSTAR_TOKEN: d4Soyaqc3DeOqUJCv3cESyvUk/zMelP2W6AXgZ2vX6BTpRUyGtdYVYCmUFww2IXnQCfDewFHqWvGpnjFz4HZxjoZgG/6iLeAHkzczpCqYQ2XPhzAWJtgCnQ5+0TVVL/MIJjmrxybsnB85/WIKhE/d0rkUX1KapmybYm2O8tJE+bR4S14stFVIEjMgu5U/mbP3wbVtJUPzkzTWnXwajm+tjpzAXFfWtJzoBsrUaQFqEjf7aKKdnz/NWS3rSKJ+hQixRApWKitQC2LFV9/nGBO7BwUOp/FvVoL0odQCA6vhoHFHShZEnjzA9gN8n7uBpEf5rY5PE8zyBZh57WtCvPwuzkC/o6vAmtXECbqiXog2i4zJ+MO83PgV097e8aSsixKmW/fjA0rnNiGWoTwy7DiEQZNScGcNJYFhoRkFop8DoRpfzZMye5lO478b+A+YUAcdTYtkChM9oyMYEpjrI+hqnfW9cZv3D9+KmCSR5qsAiBS1o1w7EeivXdjHw/dW5LcCX8GxRnKYsB7KYi+NgO1vXZd5m5mVYWgwrgcidl7n3+Obac4T1ywC6qWUosbWmkoI6/yxH4P2o7XlyI4NTb8IRfG8VKfq126Y0YB4nl572cuBVP4HSrMzSafXv50FEQHm5g9YQW0s++qYvyilCpO534wdBMRnO4NxkrUQy4/x1s=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
