travis:
  secure:
    BINSTAR_TOKEN: lyDgYSsgZxAZ95XkF6oBpCUmNctvSyJSxTYyYF0gAnb9fbqroExglnDzOL0gy6e7Gi1NgI12hjtqtB7tmBU8srnZIu1+SUjYthura7qjDhNllo6ipwV2O0/aO5G2jPk9QZNAVl5vNJCANeVYBhq8CCS69paCrn8wSJXwN3ovKotXepAq1oAfnTz4iHtxRGTYfpfT3MIQqueFI6+WV3GHyZX/gSG7EMI3DSFVHKaCNnWsRrBmYmH20KfQdSQSq6DZIEJIGQIVeV7qc73zKdJAzuSuxuHVSg6zNDcddok8MM46YBiVw7YAinfXAevUi178iabiZz3Nato0mMLX/qToD6GX+qHjMo9Azs3RXmTs/9Gqz2Vtnk+wkDSG0nWFbxubYn9MgVhKkS6FMUmBrD9oNNQ50+j4Ej/Q8aWEjzRv+MsQuPPqyUh/BR7+JuDwKQPRXnJYOnUZFH0wiU2cU6Gauc3u60MTalsVBn5w4RD9epYjIGMCSC3VMKoFnoXvM+eK9kZxgefBjggwZPMGyn9WfeTdVEIeJxV4PfS24gmOKlNaNHEvb8vcqU/yS1Z0XvOKHz/TWhMuKPPHfgKhCQLCg7vDydOjzLY/jEGxhmcONNZs7OqqTfFUB/xM+ZUO3lhYyz7DmVdF2UPS7JUL4wkof0agSZcAh8oUjVByK84JEGU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
